# The Address of our Docker Database
spring.datasource.url=jdbc:postgresql://localhost:5432/manager_db
spring.datasource.username=amine
spring.datasource.password=password123

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Old version (H2)
#spring.application.name=manager

#Affiche les commandes SQL (last used was with H2)
#spring.jpa.show-sql=true